spring:
  application:
    name: payment
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment}
    username: ${SPRING_DATASOURCE_USERNAME:payment}
    password: ${SPRING_DATASOURCE_PASSWORD:payment}
  flyway:
    enabled: true
    locations: classpath:db/migration
    fail-on-missing-locations: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8080}

payment:
  authorizer:
    base-url: ${PAYMENT_AUTHORIZER_BASE_URL:https://util.devi.tools}
    connect-timeout: 2s
    read-timeout: 2s
